### ISSUE TITLE
On Desktop: Product Image 

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/HavensCreamery#6]
On any of the product pages (On Desktop) the product image should scroll / float down along side the options as the user selects them.

![screen shot 2017-03-05 at 2 55 44 pm](https://cloud.githubusercontent.com/assets/10511034/23590789/68328302-01b4-11e7-9b76-0ad94ee110f0.png)

**Comment by nitubasra** [comment]
I have fixed this issue you can check at the link given below
http://havenscreamery.com/shop/cakes/ice-cream-cake/

**Comment by sgerritse** [comment]
It seems to disappear once its reached bottom.

Please just make it static image that moves, not disappears.

**Comment by sgerritse** [comment]
On Desktop, it seems to push the product beyond the "related products":
![screen shot 2017-03-19 at 5 42 06 pm](https://cloud.githubusercontent.com/assets/10511034/24085073/8db19df8-0ccb-11e7-8e4e-5aef2c0073be.png)
![screen shot 2017-03-19 at 5 42 12 pm](https://cloud.githubusercontent.com/assets/10511034/24085072/8dae50da-0ccb-11e7-8922-ae03fd0ee3dc.png)

When on desktop it should not go past the "SKU: N/A Category:"
![screen shot 2017-03-19 at 5 42 21 pm](https://cloud.githubusercontent.com/assets/10511034/24085113/0c86b8b6-0ccc-11e7-9cf6-d3e8d8f9449a.jpg)

**Comment by sumeena** [comment]
issue resolved.

**Comment by sgerritse** [comment]
This issue still remains for the top:
![screen shot 2017-03-20 at 8 00 31 pm](https://cloud.githubusercontent.com/assets/10511034/24127027/00958db6-0da8-11e7-8f42-2da3c8deb2c8.png)

**Comment by sumeena** [comment]
issue resolved.
